
txt2img:
  "sd_model_key": "stablediffusionapi/architecturerealmix"
  "prompt": "Picture of a modern building, high quality"
  "negative_prompt": "sketch"
  "seed": 1713428430
  "width": 1024
  "height": 512
  "num_images_per_prompt": 1
  "guidance_scale": 7.0
  "num_inference_steps": 20
  "controlnet_units":
    - "preprocessor": "none"
      "controlnet_key": "lllyasviel/sd-controlnet-depth"
      "condition_image_path":
      "weight": 1.0


inpaint:
  "sd_model_key": "stablediffusionapi/architecturerealmix"
  # run
  "image_path":
  "mask_path":
  "prompt":
  "negative_prompt":
  "seed":
  "width": 1024
  "height": 512
  "num_images_per_prompt": 1
  "guidance_scale": 3.0
  "num_inference_steps": 20
  "denoising_strength": 1.0
  "controlnet_units":
    - "preprocessor": "none"
      "controlnet_key": "lllyasviel/sd-controlnet-depth"
      "condition_image_path":
      "weight": 1.0
    - "preprocessor": "inpaint_global_harmonious"
      "controlnet_key": "lllyasviel/control_v11p_sd15_inpaint"
      "condition_image_path": ""
      "weight": 0.5

